# Generated by Django 2.2.17 on 2021-04-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_auto_20210318_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shopapp.ProductCategory'),
        ),
    ]
