# Generated by Django 2.2.17 on 2021-04-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_auto_20210405_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoty',
            new_name='category',
        ),
    ]
